server:
  port: 9999
spring:
  application:
    name: microservice-config-server
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'

    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/Xu295/Config.git
          # Git仓库账号
          username: 2953551244@qq.com
          # Git仓库密码
          password: Ilikelml1314
          skip-ssl-validation: true